### ISSUE TITLE
Invalid OpenAI key error, after editing config.json

### ISSUE THREAD

**Issue by acemagex** [vienteck/ComfyUI-Chat-GPT-Integration#4]
Hey there, I'm trying to get your ComfyUI ChatGPT Integration node working, and I've got it installed fine, but even after editing the config.json and verifying with a brand new API key, the ComfyUI console still displays that the API key is invalid, and OpenAI features won't work for me. Is there a known fix for this?

**Comment by vienteck** [comment]
Make sure you reset the server once you edit the config file.
