### ISSUE TITLE
Why pollute response with unnecessary text? 

### ISSUE THREAD

**Issue by madvas** [vienteck/ComfyUI-Chat-GPT-Integration#5]
Hey, I appreciate your custom node, it's very useful, but why on earth would you do this? https://github.com/vienteck/ComfyUI-Chat-GPT-Integration/blob/main/chat_gpt_integration.py#L125

I want to use response as a image prompt directly, I can't have that text around it. Please consider removing it, or at least give some option for people who want output without it. Thank you.

**Comment by vienteck** [comment]
I will take a look at it today and see what I can do. I’ll update here as soon as I’m done

**Comment by vienteck** [comment]
Okay I have pushed a change out so now only the response from OpenAI will be passed into the image generator.
