### ISSUE TITLE
OpenAI API key not found

### ISSUE THREAD

**Issue by alessandroperilli** [vienteck/ComfyUI-Chat-GPT-Integration#6]
Hi Victor. First of all, thanks for picking up where Omar left. His nodes have stopped working due to the changes in the OpenAI API.

So I am testing if I can use your node as a replacement for his in the upcoming [AP Workflow 9.0 for ComfyUI](https://perilli.com/ai/comfyui/). The first problem I have is that the node cannot find the API key, despite I correctly put it in the config.json file.

I'm on macOS, and this is the error I get:

> getting models
> getting ai models
> Config File Location: /ComfyUI/custom_nodes/ComfyUI-Chat-GPT-Integration\config.json
> Error: OpenAI API key file not found OpenAI features wont work for you
> Error: OpenAI API key is invalid OpenAI features wont work for you
> Roles File Location: /ComfyUI/custom_nodes/ComfyUI-Chat-GPT-Integration\roles.json
> Error: OpenAI API key file not found OpenAI features wont work for you
> FETCH DATA from: /ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
> getting models
> Roles File Location: /ComfyUI/custom_nodes/ComfyUI-Chat-GPT-Integration\roles.json
> Error: OpenAI API key file not found OpenAI features wont work for you

The slash looks wrong, so maybe it's a simple syntax problem in the python code?

(I edited the config.json and restart ComfyUI. It made no difference.)

Thanks for your help!

**Comment by vienteck** [comment]
I have pushed an update out. Please let me know if it works for you.

**Comment by alessandroperilli** [comment]
This fixed it, thanks @vienteck!
